"""initial

Revision ID: 3d8fd69486a6
Revises: 9338fa509b42
Create Date: 2024-06-04 01:40:24.820230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d8fd69486a6'
down_revision = '9338fa509b42'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
