version: '3.9'

networks:
  dev-network:
    driver: bridge

services:
  db:
    image: postgres:16-alpine
    env_file:
      - ./.env
    restart: always
    ports:
        - "5432:5432"
    volumes:
        - db-data:/var/lib/postgresql/data
        - ./scripts:/docker-entrypoint-initdb.d
    networks:
        - dev-network
  test-db:
    image: postgres:16-alpine
    env_file:
      - ./.env
    restart: always
    ports:
      - "5434:5434"
    volumes:
      - test-db-data:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d
    networks:
      - dev-network
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: [
      'hypercorn',
        'app.main:app',
        '--reload',
        '--bind',
        '0.0.0.0:8000',
    ]
    env_file:
      - ./.env
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
      - test-db
    links:
      - db
      - test-db
    volumes:
      - type: bind
        source: .
        target: /usr/src/app/
    networks:
        - dev-network
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
      - test-db
    links:
      - db
      - test-db
    networks:
        - dev-network


volumes:
    db-data:
    test-db-data: